LEVEL_MUSIC = {
    'ebonwood': 'assets/sounds/level/ebonwood.ogg',
    'cave': 'assets/sounds/level/cave.ogg',
    'moor': 'assets/sounds/level/moor.ogg',
    'cavern': 'assets/sounds/level/cavern.ogg',
    'ruins': 'assets/sounds/level/ruins.ogg',
    'icebound': 'assets/sounds/level/icebound.ogg',
    'cursed': 'assets/sounds/level/cursed.ogg'
}

ACTION_SOUNDS = {
    'chest': 'assets/sounds/misc/chest.ogg',
    'item-drop': 'assets/sounds/misc/item-drop.ogg',
    'item-move': 'assets/sounds/misc/item-move.ogg',
    'item-pick': 'assets/sounds/misc/item-pick.ogg',
    'drink': 'assets/sounds/misc/drink.ogg',
    'potion': 'assets/sounds/misc/potion.ogg',
    'waypoint': 'assets/sounds/misc/waypoint.ogg',
    'button': 'assets/sounds/misc/button.ogg',
    'pause': 'assets/sounds/misc/pause.ogg',
    'unpause': 'assets/sounds/misc/unpause.ogg',
    'attack1': 'assets/sounds/misc/attack1.ogg',
    'attack2': 'assets/sounds/misc/attack2.ogg',
    'attack3': 'assets/sounds/misc/attack3.ogg',
    'attack4': 'assets/sounds/misc/attack4.ogg',
    'die': 'assets/sounds/misc/die.ogg',
    'death': 'assets/sounds/misc/death.ogg',
    'kick': 'assets/sounds/spells/kick.ogg',
    'clash': 'assets/sounds/spells/clash.ogg',
    'whirlwind': 'assets/sounds/spells/whirlwind.ogg',
    'fireball': 'assets/sounds/spells/fireball.ogg',
    'fireball-burst': 'assets/sounds/spells/fireball-burst.ogg',
    'icebolt': 'assets/sounds/spells/icebolt.ogg',
    'icebolt-burst': 'assets/sounds/spells/icebolt-burst.ogg',
    'lightning': 'assets/sounds/spells/lightning.ogg',
    'forcepush': 'assets/sounds/spells/forcepush.ogg',
    'teleport': 'assets/sounds/spells/teleport.ogg',
    'demon-teleport': 'assets/sounds/spells/demon-teleport.ogg',
}

FOOTSTEP_SOUNDS = {
    "grass": [
        "assets/sounds/footsteps/grass1.ogg",
        "assets/sounds/footsteps/grass2.ogg",
        "assets/sounds/footsteps/grass3.ogg",
        "assets/sounds/footsteps/grass4.ogg",
    ],
    "concrete": [
        "assets/sounds/footsteps/concrete1.ogg",
        "assets/sounds/footsteps/concrete2.ogg",
        "assets/sounds/footsteps/concrete3.ogg",
        "assets/sounds/footsteps/concrete4.ogg",
    ],
    "snow": [
        "assets/sounds/footsteps/snow1.ogg",
        "assets/sounds/footsteps/snow2.ogg",
        "assets/sounds/footsteps/snow3.ogg",
        "assets/sounds/footsteps/snow4.ogg",
    ],
}

ENEMIES_SOUNDS = {
    'goblin1': 'assets/sounds/enemies/goblin1.ogg',
    'goblin2': 'assets/sounds/enemies/goblin2.ogg',
    'goblindie': 'assets/sounds/enemies/goblindie.ogg',
    'goblinshamandie': 'assets/sounds/enemies/goblindie.ogg',
    'skeleton1': 'assets/sounds/enemies/skeleton1.ogg',
    'skeleton2': 'assets/sounds/enemies/skeleton2.ogg',
    'skeletondie': 'assets/sounds/enemies/skeletondie.ogg',
    'skeletonoccultistdie': 'assets/sounds/enemies/skeletondie.ogg',
    'skeletonknight1': 'assets/sounds/enemies/skeletonknight1.ogg',
    'skeletonknight2': 'assets/sounds/enemies/skeletonknight2.ogg',
    'skeletonknightdie': 'assets/sounds/enemies/skeletonknightdie.ogg',
    'spider1': 'assets/sounds/enemies/spider1.ogg',
    'spider2': 'assets/sounds/enemies/spider2.ogg',
    'spiderdie': 'assets/sounds/enemies/spiderdie.ogg',
    'zombie1': 'assets/sounds/enemies/zombie1.ogg',
    'zombie2': 'assets/sounds/enemies/zombie2.ogg',
    'zombiedie': 'assets/sounds/enemies/zombiedie.ogg',
    'darkzombie1': 'assets/sounds/enemies/darkzombie1.ogg',
    'darkzombie2': 'assets/sounds/enemies/darkzombie2.ogg',
    'darkzombiedie': 'assets/sounds/enemies/darkzombiedie.ogg',
    'cursedknight1': 'assets/sounds/enemies/cursedknight1.ogg',
    'cursedknight2': 'assets/sounds/enemies/cursedknight2.ogg',
    'cursedknightdie': 'assets/sounds/enemies/cursedknightdie.ogg',
    'werewolf1': 'assets/sounds/enemies/werewolf1.ogg',
    'werewolf2': 'assets/sounds/enemies/werewolf2.ogg',
    'werewolfdie': 'assets/sounds/enemies/werewolfdie.ogg',
    'antilion1': 'assets/sounds/enemies/antilion1.ogg',
    'antilion2': 'assets/sounds/enemies/antilion2.ogg',
    'antiliondie': 'assets/sounds/enemies/antiliondie.ogg',
    'werebear1': 'assets/sounds/enemies/werebear1.ogg',
    'werebear2': 'assets/sounds/enemies/werebear2.ogg',
    'werebeardie': 'assets/sounds/enemies/werebeardie.ogg',
    'minotaur1': 'assets/sounds/enemies/minotaur1.ogg',
    'minotaur2': 'assets/sounds/enemies/minotaur2.ogg',
    'minotaurdie': 'assets/sounds/enemies/minotaurdie.ogg',
    'golem1': 'assets/sounds/enemies/golem1.ogg',
    'golem2': 'assets/sounds/enemies/golem2.ogg',
    'golemdie': 'assets/sounds/enemies/golemdie.ogg',
    'wyvern1': 'assets/sounds/enemies/wyvern1.ogg',
    'wyvern2': 'assets/sounds/enemies/wyvern2.ogg',
    'wyverndie': 'assets/sounds/enemies/wyverndie.ogg',
    'icewyvern1': 'assets/sounds/enemies/icewyvern1.ogg',
    'icewyvern2': 'assets/sounds/enemies/icewyvern2.ogg',
    'icewyverndie': 'assets/sounds/enemies/icewyverndie.ogg',
    'demon0': 'assets/sounds/enemies/demon0.ogg',
    'demon1': 'assets/sounds/enemies/demon1.ogg',
    'demon2': 'assets/sounds/enemies/demon2.ogg',
    'demon3': 'assets/sounds/enemies/demon3.ogg',
    'demon4': 'assets/sounds/enemies/demon4.ogg',
    'demon5': 'assets/sounds/enemies/demon5.ogg',
    'demondie': 'assets/sounds/enemies/demondie.ogg',
}